require("packer-setup")
require("core.options")

require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.nvim-cmp")
require("plugins.telescope")
require("plugins.autopairs")

require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
