require("plugin-setup")
require("core.options")
require("core.keymaps")

require("plugins.autopairs")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.nvim-cmp")
require("plugins.telescope")
require("plugins.autopairs")
require("plugins.neoscroll")
require("plugins.ccc")
require("plugins.leap")
require("plugins.colorizer")
require("plugins.dressing")
require("plugins.coc")

require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")

require("plugins.tokyonight")
require("core.colorscheme")
